<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519191038 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE droid_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE starship_droid_id_seq CASCADE');
        $this->addSql('ALTER TABLE starship_droid DROP CONSTRAINT fk_1c7fbe88ab064ef');
        $this->addSql('ALTER TABLE starship_droid DROP CONSTRAINT fk_1c7fbe889b24df5');
        $this->addSql('DROP TABLE starship_droid');
        $this->addSql('DROP TABLE droid');
        $this->addSql('ALTER TABLE starship ALTER id TYPE INT');
        $this->addSql('ALTER TABLE starship ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE starship ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE starship ALTER arrived_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN starship.arrived_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_2a37b570989d9b62 RENAME TO UNIQ_C414E64A989D9B62');
        $this->addSql('ALTER TABLE starship_part DROP CONSTRAINT fk_41c447379b24df5');
        $this->addSql('DROP INDEX idx_41c447379b24df5');
        $this->addSql('ALTER TABLE starship_part DROP starship_id');
        $this->addSql('ALTER TABLE starship_part DROP created_at');
        $this->addSql('ALTER TABLE starship_part DROP updated_at');
        $this->addSql('ALTER TABLE starship_part ALTER id TYPE INT');
        $this->addSql('ALTER TABLE starship_part ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE starship_part ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE starship_part ALTER price TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE starship_part ALTER notes TYPE TEXT');
        $this->addSql('ALTER TABLE starship_part ALTER notes SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE droid_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE starship_droid_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE starship_droid (id INT DEFAULT starship_droid_id_seq NOT NULL, droid_id INT NOT NULL, starship_id INT NOT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_1c7fbe889b24df5 ON starship_droid (starship_id)');
        $this->addSql('CREATE INDEX idx_1c7fbe88ab064ef ON starship_droid (droid_id)');
        $this->addSql('COMMENT ON COLUMN starship_droid.assigned_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE droid (id INT DEFAULT droid_id_seq NOT NULL, name VARCHAR(255) NOT NULL, primary_function VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE starship_droid ADD CONSTRAINT fk_1c7fbe88ab064ef FOREIGN KEY (droid_id) REFERENCES droid (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE starship_droid ADD CONSTRAINT fk_1c7fbe889b24df5 FOREIGN KEY (starship_id) REFERENCES starship (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE starship ALTER id TYPE INT');
        $this->addSql('ALTER TABLE starship ALTER id SET DEFAULT starship_id_seq');
        $this->addSql('ALTER TABLE starship ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE starship ALTER arrived_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN starship.arrived_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_c414e64a989d9b62 RENAME TO uniq_2a37b570989d9b62');
        $this->addSql('ALTER TABLE starship_part ADD starship_id INT NOT NULL');
        $this->addSql('ALTER TABLE starship_part ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE starship_part ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE starship_part ALTER id TYPE INT');
        $this->addSql('ALTER TABLE starship_part ALTER id SET DEFAULT starship_part_id_seq');
        $this->addSql('ALTER TABLE starship_part ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE starship_part ALTER price TYPE INT');
        $this->addSql('ALTER TABLE starship_part ALTER notes TYPE TEXT');
        $this->addSql('ALTER TABLE starship_part ALTER notes DROP NOT NULL');
        $this->addSql('ALTER TABLE starship_part ADD CONSTRAINT fk_41c447379b24df5 FOREIGN KEY (starship_id) REFERENCES starship (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_41c447379b24df5 ON starship_part (starship_id)');
    }
}
